### PR TITLE
MAINT: differential_evolution refactored loops and ensured that use of args tuple works in a parallel context.

### PR DESCRIPTION
**Pull request by andyfaff**
- Eliminated several loops to vectorise code.
- made sure that calling objective function works in parallel context (it wouldn't have worked with the `args` tuple)
- added tests to see if the code works in a parallel context (with and without `args` tuple)
- reformatted documentation
- added documentation to note that the objective function needs to be pickleable in a parallel context (you're going to crash your program otherwise).

Might need to add test in solver to see if an objective function is pickleable rather than crashing the program outright.

### CODE REVIEW

**Comment by andyfaff** [comment]
If you do decide to merge this into your branch, then it might be better to have your branch up to date with scipy/master.  I'm not a git expert...

**Comment by andyfaff** [comment]
maps return iterators in python3, not lists as in python2

**Comment by andyfaff** [comment]
It's probably easier if `PPool` extends `multiprocessing.pool.Pool`, in that way we get all the `Pool` methods. All we have to add is the `poolsize` method

**Comment by pavelponomarev** [comment]
If neither of us is an experts in GIT, it'd been easier if you'd made your modifications based on this parDE branch which is used for the PR. I am not sure how to resolve these conflicts.
I agree with all your changes. How do we proceed then?

**Comment by pavelponomarev** [comment]
OK, probably a rebasing of this branch will help http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#rebasing-on-master.
I will do it and review these commits until the end of this week.

**Comment by andyfaff** [comment]
> If neither of us is an experts in GIT, it'd been easier if you'd made your
> modifications based on this parDE brunch which is used for the PR. I am not
> sure how to resolve these conflicts.
> I agree with all your changes. How do we proceed then?
> 
> To make the changes I made a feature branch (called parDE) from my master
> branch. My master branch was up to date with all changes from scipy/master.
> I then pulled your parDE branch onto mine. I _think_ it'll work if you
> rebase your parDE on scipy/master.

**Pull request merged**
